# Generated by Django 5.2.3 on 2025-07-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vedomost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_f', models.CharField(blank=True, max_length=100, null=True)),
                ('doc', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('buls', models.CharField(blank=True, max_length=100, null=True)),
                ('opisanie', models.TextField(blank=True, null=True)),
                ('suma', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debit', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
