# Generated by Django 5.2.3 on 2025-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schetovodstvo', '0002_vedomost_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedomost',
            name='nomer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
