# Generated by Django 5.2.3 on 2025-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schetovodstvo', '0003_vedomost_nomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='smetkoplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smetka', models.IntegerField(blank=True, null=True)),
                ('opisanie', models.CharField(blank=True, max_length=100, null=True)),
                ('n_saldo_dt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('n_saldo_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('k_saldo_dt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('k_saldo_kt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
