# Generated by Django 5.2.3 on 2025-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schetovodstvo', '0004_smetkoplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='smetkoplan',
            name='spare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
